apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preproduction
metadata:
  name: preproduction
commonAnnotations:
  env: default
commonLabels:
  env: default
resources:
  - ../../base/
patches:
  - path: hpa.yaml
configMapGenerator:
  - name: parameter
    behavior: merge
    options:
      immutable: true
    files:
      - conf.yaml
images:
  - name: localhost:5000/api
    newTag: 084713-040923
configurations:
  - namespace_transform.yaml