apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
    - args:
        - sleep
        - "86400"
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/bash
              - -c
              - >
                apt update;
                apt upgrade -y;
                apt install apache2-utils -y;
                apt install curl -y;
                apt install dnsutils -y;
      image: ubuntu:latest
      name: ubuntu
      resources:
        limits:
          cpu: 400m
          memory: 128Mi
        requests:
          cpu: 150m
          memory: 32Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
