apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base

resources:
  - client_pod.yaml
  - deployment.yaml
  - hpa.yaml
  - namespace.yaml
  - sa.yaml

configMapGenerator:
  - name: parameter
    behavior: create
    options:
      immutable: true
    literals:
      - default=abc
