apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-runner-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-runner-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-runner-role
subjects:
  - kind: ServiceAccount
    name: job-runner
