apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local
metadata:
  name: local
commonAnnotations:
  env: default
commonLabels:
  env: default
resources:
  - ../../base/
configMapGenerator:
  - name: parameter
    behavior: merge
    options:
      immutable: true
    files:
      - conf.yaml
images:
  - name: localhost:5000/api
    newTag: 112528-050923
configurations:
  - namespace_transform.yaml
